In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('clean_v3.csv')

In [8]:
columns = list(df.columns)
(columns[:24])

['LotArea',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'SalePrice',
 'MasVnrType',
 'ExterQual',
 'BsmtQual',
 'KitchenQual',
 'GarageFinish']

In [9]:
df = df[columns[:24]]

In [10]:
df = df.dropna()

In [11]:
df1 = pd.get_dummies(df, drop_first=True)

In [12]:
df1.head()

LotArea  OverallQual  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
0     8450            7       2003          2003       196.0         706   
1     9600            6       1976          1976         0.0         978   
2    11250            7       2001          2002       162.0         486   
3     9550            7       1915          1970         0.0         216   
4    14260            8       2000          2000       350.0         655   

   TotalBsmtSF  1stFlrSF  2ndFlrSF  GrLivArea  ...  ExterQual_Gd  \
0          856       856       854       1710  ...             1   
1         1262      1262         0       1262  ...             0   
2          920       920       866       1786  ...             1   
3          756       961       756       1717  ...             0   
4         1145      1145      1053       2198  ...             1   

   ExterQual_TA  BsmtQual_Fa  BsmtQual_Gd  BsmtQual_TA  KitchenQual_Fa  \
0             0            0            1            0               0   
1             1            0            1            0               0   
2             0            0            1            0               0   
3             1            0            0            1               0   
4             0            0            1            0               0   

   KitchenQual_Gd  KitchenQual_TA  GarageFinish_RFn  GarageFinish_Unf  
0               1               0                 1                 0  
1               0               1                 1                 0  
2               1               0                 1                 0  
3               1               0                 0                 1  
4               1               0                 1                 0  

[5 rows x 33 columns]

In [13]:
X = df1.drop('SalePrice', axis = 1)
y = df1['SalePrice']

## 1. Linear Regression
# 


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [15]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.8154293050257942

In [16]:
from sklearn.model_selection import cross_val_score
clf = lr
scores = cross_val_score(clf, X, y, cv=5)
scores

array([0.85594014, 0.78604297, 0.82860858, 0.83251151, 0.5932701 ])

## 2. Random Forest
# 

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
rfr = RandomForestRegressor(n_estimators=150, min_samples_split=5)
rfr.fit(X_train, y_train)
rfr.score(X_test, y_test)

0.8520197057139993

In [21]:
from sklearn.model_selection import cross_val_score
r_clf = rfr
scores = cross_val_score(r_clf, X, y, cv=5)
scores

array([0.85102409, 0.83076718, 0.87567016, 0.88373623, 0.81243874])

In [26]:
len(df.columns)

24

## Gradient Boosting

In [29]:
from sklearn.ensemble import GradientBoostingRegressor

In [30]:
gbc = GradientBoostingRegressor()
gbc.fit(X_train, y_train)
gbc.score(X_test, y_test)

0.818775749048044

In [31]:
g_clf = gbc
scores = cross_val_score(g_clf, X, y, cv=5)
scores

array([0.88884974, 0.82852296, 0.88815887, 0.89595586, 0.87416904])

In [ ]:
X_columns = 

## Implementing Gradient Boosting in Final Model

In [32]:
X = df1.drop('SalePrice', axis = 1)
y = df1['SalePrice']

In [34]:
df_test = pd.read_csv('test.csv')

In [40]:
df_test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [33]:
from sklearn.ensemble import GradientBoostingRegressor

In [42]:
gbc = GradientBoostingRegressor()
gbc.fit(X, y)
gbc.score(X, y)

0.9537128140468898

In [43]:
import pickle

In [44]:
# Save the Modle to file in the current working directory

Pkl_Filename = "house_predict_GBR.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(gbc, file)

In [45]:
# Predicting test values

In [135]:
df_test = pd.read_csv('test.csv')

In [136]:
df_test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [137]:
t_c = columns
t_c

['LotArea',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'MasVnrType',
 'ExterQual',
 'BsmtQual',
 'KitchenQual',
 'GarageFinish']

In [138]:
t_c.remove('SalePrice.1')
t_c

ValueError: list.remove(x): x not in list

In [139]:
len(t_c)

23

In [140]:
df_test = df_test[t_c]

In [141]:
df_test['MasVnrArea'].value_counts()

0.0      877
176.0     10
144.0      9
120.0      8
216.0      8
        ... 
634.0      1
177.0      1
615.0      1
549.0      1
442.0      1
Name: MasVnrArea, Length: 303, dtype: int64

In [142]:
df_test['MasVnrArea'].replace(np.nan, 0, inplace = True)

In [143]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 23 columns):
LotArea         1459 non-null int64
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1459 non-null float64
BsmtFinSF1      1458 non-null float64
TotalBsmtSF     1458 non-null float64
1stFlrSF        1459 non-null int64
2ndFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1381 non-null float64
GarageCars      1458 non-null float64
GarageArea      1458 non-null float64
WoodDeckSF      1459 non-null int64
OpenPorchSF     1459 non-null int64
MasVnrType      1443 non-null object
ExterQual       1459 non-null object
BsmtQual        1415 non-null object
KitchenQual     1458 non-null object
GarageFinish    1381 non-null object
dtypes: float64(6), int64(12), object(5)
memory 

In [144]:
df_test['BsmtFinSF1'].value_counts()

0.0       462
24.0       15
276.0       6
602.0       6
300.0       5
         ... 
278.0       1
210.0       1
580.0       1
1328.0      1
771.0       1
Name: BsmtFinSF1, Length: 669, dtype: int64

In [145]:
df_test['BsmtFinSF1'].replace(np.nan, 0, inplace = True)

In [146]:
df_test['TotalBsmtSF'].value_counts()

0.0       41
864.0     39
960.0     13
546.0     12
672.0     12
          ..
918.0      1
1910.0     1
1700.0     1
750.0      1
1075.0     1
Name: TotalBsmtSF, Length: 736, dtype: int64

In [147]:
df_test['TotalBsmtSF'].replace(np.nan, 0, inplace = True)

In [148]:
df_test['GarageYrBlt'].value_counts()

2005.0    77
2007.0    66
2006.0    56
2004.0    46
2003.0    42
          ..
1918.0     1
1895.0     1
1919.0     1
1896.0     1
1916.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

In [149]:
df_test['YearBuilt'].value_counts()

2005    78
2006    71
2007    60
2004    45
2003    43
        ..
1902     1
1896     1
1982     1
1880     1
1879     1
Name: YearBuilt, Length: 106, dtype: int64

In [150]:
#df_test['GarageYrBlt'] = df_test['GarageYrBlt'].fillna(df_test['YearBuilt'])
df_test['GarageYrBlt'].replace(np.nan, df_test['YearBuilt'], inplace = True)

In [151]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 23 columns):
LotArea         1459 non-null int64
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1459 non-null float64
BsmtFinSF1      1459 non-null float64
TotalBsmtSF     1459 non-null float64
1stFlrSF        1459 non-null int64
2ndFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1459 non-null float64
GarageCars      1458 non-null float64
GarageArea      1458 non-null float64
WoodDeckSF      1459 non-null int64
OpenPorchSF     1459 non-null int64
MasVnrType      1443 non-null object
ExterQual       1459 non-null object
BsmtQual        1415 non-null object
KitchenQual     1458 non-null object
GarageFinish    1381 non-null object
dtypes: float64(6), int64(12), object(5)
memory 

In [152]:
df_test['GarageCars'].value_counts()

2.0    770
1.0    407
3.0    193
0.0     76
4.0     11
5.0      1
Name: GarageCars, dtype: int64

In [153]:
df_test['GarageCars'].replace(np.nan, 2, inplace = True)

In [155]:
df_test['GarageArea'].mean()

472.76886145404666

In [156]:
df_test['GarageArea'].replace(np.nan, df_test['GarageArea'].mean(), inplace = True)

In [157]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 23 columns):
LotArea         1459 non-null int64
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1459 non-null float64
BsmtFinSF1      1459 non-null float64
TotalBsmtSF     1459 non-null float64
1stFlrSF        1459 non-null int64
2ndFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1459 non-null float64
GarageCars      1459 non-null float64
GarageArea      1459 non-null float64
WoodDeckSF      1459 non-null int64
OpenPorchSF     1459 non-null int64
MasVnrType      1443 non-null object
ExterQual       1459 non-null object
BsmtQual        1415 non-null object
KitchenQual     1458 non-null object
GarageFinish    1381 non-null object
dtypes: float64(6), int64(12), object(5)
memory 

In [158]:
df['MasVnrType'].value_counts()

None       772
BrkFace    434
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

In [159]:
df_test['MasVnrType'].replace(np.nan, 'None', inplace = True)

In [161]:
df_test['MasVnrType'].value_counts()

None       894
BrkFace    434
Stone      121
BrkCmn      10
Name: MasVnrType, dtype: int64

In [162]:
df_test['BsmtQual'].value_counts()

TA    634
Gd    591
Ex    137
Fa     53
Name: BsmtQual, dtype: int64

In [163]:
df_test['BsmtQual'].replace(np.nan, 'TA', inplace = True)

In [164]:
df_test['BsmtQual'].value_counts()

TA    678
Gd    591
Ex    137
Fa     53
Name: BsmtQual, dtype: int64

In [165]:
df_test['KitchenQual'].value_counts()

TA    757
Gd    565
Ex    105
Fa     31
Name: KitchenQual, dtype: int64

In [166]:
df_test['KitchenQual'].replace(np.nan, 'TA', inplace = True)

In [167]:
df_test['GarageFinish'].value_counts()

Unf    625
RFn    389
Fin    367
Name: GarageFinish, dtype: int64

In [168]:
df_test['GarageFinish'].replace(np.nan, 'Unf', inplace = True)

In [169]:
df_test['GarageFinish'].value_counts()

Unf    703
RFn    389
Fin    367
Name: GarageFinish, dtype: int64

In [170]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 23 columns):
LotArea         1459 non-null int64
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1459 non-null float64
BsmtFinSF1      1459 non-null float64
TotalBsmtSF     1459 non-null float64
1stFlrSF        1459 non-null int64
2ndFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1459 non-null float64
GarageCars      1459 non-null float64
GarageArea      1459 non-null float64
WoodDeckSF      1459 non-null int64
OpenPorchSF     1459 non-null int64
MasVnrType      1459 non-null object
ExterQual       1459 non-null object
BsmtQual        1459 non-null object
KitchenQual     1459 non-null object
GarageFinish    1459 non-null object
dtypes: float64(6), int64(12), object(5)
memory 

In [171]:
df_test = pd.get_dummies(df_test, drop_first=True)
df_test.head()

LotArea  OverallQual  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
0    11622            5       1961          1961         0.0       468.0   
1    14267            6       1958          1958       108.0       923.0   
2    13830            5       1997          1998         0.0       791.0   
3     9978            6       1998          1998        20.0       602.0   
4     5005            8       1992          1992         0.0       263.0   

   TotalBsmtSF  1stFlrSF  2ndFlrSF  GrLivArea  ...  ExterQual_Gd  \
0        882.0       896         0        896  ...             0   
1       1329.0      1329         0       1329  ...             0   
2        928.0       928       701       1629  ...             0   
3        926.0       926       678       1604  ...             0   
4       1280.0      1280         0       1280  ...             1   

   ExterQual_TA  BsmtQual_Fa  BsmtQual_Gd  BsmtQual_TA  KitchenQual_Fa  \
0             1            0            0            1               0   
1             1            0            0            1               0   
2             1            0            1            0               0   
3             1            0            0            1               0   
4             0            0            1            0               0   

   KitchenQual_Gd  KitchenQual_TA  GarageFinish_RFn  GarageFinish_Unf  
0               0               1                 0                 1  
1               1               0                 0                 1  
2               0               1                 0                 0  
3               1               0                 0                 0  
4               1               0                 1                 0  

[5 rows x 32 columns]

In [172]:
df_test.columns

Index(['LotArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea',
       'BsmtFinSF1', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars',
       'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'MasVnrType_BrkFace',
       'MasVnrType_None', 'MasVnrType_Stone', 'ExterQual_Fa', 'ExterQual_Gd',
       'ExterQual_TA', 'BsmtQual_Fa', 'BsmtQual_Gd', 'BsmtQual_TA',
       'KitchenQual_Fa', 'KitchenQual_Gd', 'KitchenQual_TA',
       'GarageFinish_RFn', 'GarageFinish_Unf'],
      dtype='object')

In [174]:
X.columns

Index(['LotArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea',
       'BsmtFinSF1', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars',
       'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'MasVnrType_BrkFace',
       'MasVnrType_None', 'MasVnrType_Stone', 'ExterQual_Fa', 'ExterQual_Gd',
       'ExterQual_TA', 'BsmtQual_Fa', 'BsmtQual_Gd', 'BsmtQual_TA',
       'KitchenQual_Fa', 'KitchenQual_Gd', 'KitchenQual_TA',
       'GarageFinish_RFn', 'GarageFinish_Unf'],
      dtype='object')

In [175]:
X_test = df_test
y_test = gbc.predict(X_test) # SalePrice Predicted

In [176]:
y_test

array([127233.85201796, 169341.88679081, 181736.08078118, ...,
       174134.64368208, 124150.05161579, 230926.13796426])

In [177]:
submission = pd.read_csv('test.csv') 

In [178]:
submission['SalePrice'] = y_test

In [179]:
submission.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1         Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4         HLS    AllPub  ...        0    NaN    NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition      SalePrice  
0      6   2010        WD         Normal  127233.852018  
1      6   2010        WD         Normal  169341.886791  
2      3   2010        WD         Normal  181736.080781  
3      6   2010        WD         Normal  181877.246370  
4      1   2010        WD         Normal  195567.673808  

[5 rows x 81 columns]

In [182]:
submission = submission[['Id', 'SalePrice']]

In [183]:
submission.head()

Id      SalePrice
0  1461  127233.852018
1  1462  169341.886791
2  1463  181736.080781
3  1464  181877.246370
4  1465  195567.673808

In [186]:
submission.to_csv('final_submission.csv', index = False)